FROM tajo9128/biodockify-ai:v3.9.0

COPY webui/ /a0/webui/
COPY plugins/ /a0/plugins/
COPY public/ /a0/webui/public/

RUN cp -r /a0/webui/. /git/agent-zero/webui/ && \
    cp -r /a0/plugins/. /git/agent-zero/plugins/
